version: '3.9'

services:
  db:
    image: bitnami/postgresql:latest
    container_name: postgres-db
    platform: linux/x86_64
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgres
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      timeout: 10s
      retries: 5

networks:
  default:
    name: todo-app-net